version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - RATELIMIT_STORAGE_URI=redis://redis:6379/0
    volumes:
      - ./instance:/app/instance
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
