from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.utils.analytics import dashboard_data


def build_pdf_report(user):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, title="DayTone Wellness Report")
    styles = getSampleStyleSheet()
    data = dashboard_data(user.id)
    latest = data["latest"]

    story = [
        Paragraph("DayTone Wellness Report", styles["Title"]),
        Paragraph(f"User: {user.name}", styles["Normal"]),
        Paragraph("Generated by DayTone AI Mental Wellness Tracker", styles["Normal"]),
        Spacer(1, 18),
        Paragraph("Summary", styles["Heading2"]),
    ]

    summary = Table(
        [
            ["Total Logs", len(data["labels"])],
            ["Average Mood", data["avg_mood"]],
            ["Average Sleep", data["avg_sleep"]],
            ["Average Stress", data["avg_stress"]],
            ["Latest Burnout Risk", latest.burnout_risk if latest else "No logs"],
        ]
    )
    summary.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke)]))
    story.extend([summary, Spacer(1, 18), Paragraph("Burnout Risk Breakdown", styles["Heading2"])])

    dist = data["burnout_distribution"]
    risk_table = Table([["Low", dist["Low"]], ["Medium", dist["Medium"]], ["High", dist["High"]]])
    risk_table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey)]))
    story.extend([risk_table, Spacer(1, 18), Paragraph("Recent Mood Trend", styles["Heading2"])])

    rows = [["Date", "Mood", "Sleep", "Stress", "Risk"]]
    logs = list(zip(data["labels"], data["mood"], data["sleep"], data["stress"], data["burnout_risk_trend"]))
    for label, mood, sleep, stress, risk in logs[-10:]:
        rows.append([label, mood, sleep, stress, risk])
    trend = Table(rows)
    trend.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke)]))
    story.append(trend)

    story.extend([Spacer(1, 18), Paragraph("Top Suggestions", styles["Heading2"])])
    for suggestion in data["suggestions"][:3]:
        story.append(Paragraph(f"- {suggestion}", styles["Normal"]))

    doc.build(story)
    buffer.seek(0)
    return buffer
