"""change preferred_activity enum to string

Revision ID: 861167090cd9
Revises: b6d88f1ce836
Create Date: 2026-06-23 13:26:46.498773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861167090cd9'
down_revision = 'b6d88f1ce836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('preferred_activity',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('preferred_activity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
