"""initial schema

Revision ID: fc44d6214cbf
Revises: 
Create Date: 2026-06-11 10:42:39.457243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc44d6214cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('mood_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('activity_done', sa.Boolean(), nullable=False),
    sa.Column('social_interaction', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('burnout_risk', sa.Enum('Low', 'Medium', 'High', name='burnout_risk_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mood_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mood_log')),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_user_log_date')
    )
    with op.batch_alter_table('mood_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_log_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_log_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('preferred_activity', sa.Enum('Walk', 'Yoga', 'Music', 'Reading', name='activity_enum'), nullable=False),
    sa.Column('daily_reminder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profile_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profile_user_id'))
    )
    op.create_table('burnout_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('algorithm_used', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['mood_log.id'], name=op.f('fk_burnout_history_log_id_mood_log'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_burnout_history_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_burnout_history'))
    )
    with op.batch_alter_table('burnout_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_burnout_history_log_id'), ['log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_burnout_history_user_id'), ['user_id'], unique=False)

    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['mood_log.id'], name=op.f('fk_suggestion_log_id_mood_log'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_suggestion_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion'))
    )
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_log_id'), ['log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_user_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_log_id'))

    op.drop_table('suggestion')
    with op.batch_alter_table('burnout_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_burnout_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_burnout_history_log_id'))

    op.drop_table('burnout_history')
    op.drop_table('user_profile')
    with op.batch_alter_table('mood_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_log_log_date'))

    op.drop_table('mood_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
